name: FastAPI CI

on:
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    defaults:
      run:
        working-directory: ./hackproject/code/api/

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black
        pip install -r requirements.txt
    - name: Lint with black
      run: black ./tests && black --check ./tests
    - name: Run Tests with Pytest
      run: |
        pytest
